name: Socks Shop Deploy

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint and test
        run: |
          # Run any linting and testing scripts here

#       - name: Build Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKER_IMAGE_TAG }}

      - name: Create EKS Cluster
        uses: hashicorp/setup-terraform@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          namedotcom-token: ${{ secrets.TOKEN }}
          namedotcom-username: ${{ secrets.USERNAME }}
          aws-region: eu-west-2
      - run: |
          terraform init
          terraform apply -auto-approve
          
      - name: Deploy to Kubernetes
        uses: 

      - name: Configure Prometheus
        run: |
          # Configure Prometheus to monitor the application

      - name: Deploy complete
        run: |
          echo "Application deployed successfully!"
h
