apiVersion: v1
kind: Secret
metadata:
  name: laravel-todo-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: laravel-todo-pod
spec:
  containers:
  - name: laravel-todo
    image: laravel-todo-image
    envFrom:
    - configMapRef:
        name: laravel-todo
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: laravel-todo-secret
          key: DB_PASSWORD