apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  labels:
    app: laravel-todo
  name: laravel-todo
spec:
  rules:
    - host: webfowokeoluwole.live
      http:
        paths:
          - laravel-todo:
              serviceName: laravel-todo
              servicePort: 80
            path: /
  tls:
    - hosts:
        - webfowokeoluwole.live
      secretName: webfowokeoluwole.live-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: webfowokeoluwole.live
spec:
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
          - webfowokeoluwole.live
  commonName: webfowokeoluwole.live
  dnsNames:
    - webfowokeoluwole.live
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: webfowokeoluwole.live-tls